# Application Details
application_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# Login Credentials
admin_username=Admin
admin_password=admin123

# Browser Configuration
browser_name=chrome
headless_mode=False
